### ISSUE TITLE
Prepare for SublimeText 4 and python 3.8

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1700]
There will be a SublimeText version 4 some time in the future and it will allow plugins to run in either a python 3.3 or a 3.8 plugin host. There is no documentation yet, so there is not much we can do. Everything does seem to work just fine. But at some point we should take the jump, so this issue is just a heads-up for that.

One issue right now is that dependencies are only available in the 3.3 context. There are plans to revamp the way package control installs the plugins to make them available in 3.8. But that might be quite a while out. If 3.8 holds benefits for us we can maybe compromise on jsonschema as it's really mostly a convenience thing.

---

## TODO

- [ ] Update mockito to 1.2.x. There was a small edge-case fix necessary to get all its tests to green.
- [ ] Wait for a solution for dependencies in 3.8, or find an alternative to our jsonschema dependency

**Comment by kaste** [comment]
What's the issue when everything just works and no further details are known?  I will not suddenly use f-strings just for fun.

**Comment by braver** [comment]
Well for one thing the 3.3 host wil not see improvements or even fixes. If for one thing or another it makes sense to move to 3.8, it good to have notes somewhere about what it would take to make that move (e.g. dependencies). I'm not saying we should do anything, but I intend to have this issue as a log of what will or will not work out of the box in ST4 and perhaps areas that we can improve SL in that context.

**Comment by kaste** [comment]
Okay.

- [ ] Update `mockito` to `1.2.x`. There was a small edge-case fix necessary to get all its tests to green.

**Comment by kaste** [comment]
Closing as we don't seem to need to prepare anything for ST4 which is almost there 🍭 

Switching to 3.8 is of course not realistic as we can't update all plugins; it may be not worth it as SL is very stable and doesn't move.

**Comment by kaste** [comment]
**Maybe** we should just bulk set the python-version to `3.8` as quick as possible as we're still *alpha*.  If we hit the public beta, it will be more painful.  Does this thing work on 3.8?

**Comment by braver** [comment]
It works except there is no solution for dependencies yet. We can make the move at any time, and right now it feels like the longer we wait the easier it will be. Let’s close it now and see what the future brings.

**Comment by kaste** [comment]
Hopefully they just switch 3.3 off and we're all good.  Don't know where 3.8 wouldn't be backwards compatible.

**Comment by braver** [comment]
Oh they won’t, and I’ll keep an eye on the developments. 😉

**Comment by FichteFoll** [comment]
> Don't know where 3.8 wouldn't be backwards compatible.

There are breaking changes between 3.3 and 3.8, but most notably Python breaks ABI on every minor release and there are a couple commercial and closed source packages out there.
