### ISSUE TITLE
Panel and error-store refactoring

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#880]
As it currently reads, #822 seems to be blocking everything, but it's not clear why #822 isn't merged yet except for "This is blocked by the magic pykong PR bc otherwise he gets merge conflicts" which doesn't clarify anything 🙃 

Merge order:

- [x] #822 - ready to merge?
  - [ ] #851 - `get_we_count` must be re-implemented
  - [ ] #853 - conflicted
  - [x] #872 - approved by @FichteFoll and me
  - [x] #875 - approved by @FichteFoll and me

So, @kaste agree if I merge #822 #872 and #875?

**Comment by kaste** [comment]
Yes, merge

**Comment by braver** [comment]
Ok, #822 merged, of course everything conflicts :)

**Comment by kaste** [comment]
Yeah!
